import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" className="dark">
        <head>
            {/* iOS Safari/Chrome: пусть знают, что dark разрешён */}
            <meta name="color-scheme" content="dark light" />
        </head>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0B0D10] text-white`}
        >
        {children}
        </body>
        </html>
    );
}